{
    'name' : "Hospital Master",
    'Summary' : "All master data of hospital managed by this module",
    'version': '16.0',
    'category' : "Web Application",
    'author' : "Ajay Kumar Ravidas",
    'license': 'LGPL-3',
    'data' : [
        'security/ir.model.access.csv',
        'views/bed_details.xml',
        'views/doctor_category_details.xml',
        'views/floor_details.xml',
        'views/room_details.xml',
        'views/menuitem.xml',
    ],
    'application' : True,
    'installable': True,
    'auto_install' : False,
    'sequence' : 2,
    'price': 49.99,
    'currency': 'USD',
    'images': ['static/description/icon.jpeg'],
}